- name: deploy all
  hosts:
    - findex
  become: yes
  serial: 1
  any_errors_fatal: yes
  vars:
    git_repo: findex-gui
    git_branch: master
  roles:
    - base
    - users
    - supervisor
    - elasticsearch
    - postgres
    - rabbitmq
    - nginx
    - gui
